source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!


  pod 'pop'
  pod 'Alamofire', '~> 3.0'
  pod 'DCKit'
  pod 'JSQMessagesViewController'
  pod 'Koloda'
  pod 'FBSDKCoreKit'
  pod 'FBSDKLoginKit'
  pod 'FBSDKShareKit'
post_install do |installer|
    `find Pods -regex 'Pods/pop.*\\.h' -print0 | xargs -0 sed -i '' 's/\\(<\\)pop\\/\\(.*\\)\\(>\\)/\\"\\2\\"/'`
end
