source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '10.0'

target 'mapinte' do
     use_frameworks!
     pod 'SwiftyJSON'
     pod  'Cluster'
     pod 'Pulley'
     pod 'Localize-Swift', '~> 2.0'
end
